* 一个新世界(08/23/2013)

  上周末送郡主回了家里，我也在家里呆了一周；这一周过的不算清闲，因为虽然请假在家，我还是有很多工作要做。在处理工作之余，我开始阅读
  自己打印的<<Common Lisp>>第二版的上册，看了几章也不知道自己在看什麽；为了解惑，加入了几个讨论Lisp的QQ群，知道有一Lisp方言叫“Shen”，
  总之，一切都是美好的开端，新生命新世界的诞生。我内心满怀期待，尽管有一些惴惴不安。

  明天要回北京，今天却遇到被炒鱿鱼的危机。

  起因是上周末要给客户生成一个报告，我使用Python语言生成的。之前公司说过不准使用Python，但又模棱两可，因为公司太多程序是使用
  Python的了，公司使用的Linux就自带Python。公司希望使用C++去实现这些功能，当然最终目的是让核心引擎程序能够具备生成报
  告的feature，但目前需要一段时间的开发。

  这里就面临一个问题，在这个feature没有开发出来之前，是继续使用Python生成报告，还是使用C++生成报告。在这个问题上，我选择了Python，我
  的理由：
  #+begin_example
  1. 目前所有报告都是Python生成的，并且形成了通用库，可以很快开发出来并所有报告保持一致；
  2. 既然不是核心引擎具备这个功能，单纯的使用C++去生成报告，处理一些文本文件不是很有必要；
  3. 文本处理使用脚本语言Python，更好维护，也更好使用；
  4. 禁止使用python和shell，模棱两可，一边继续使用，一边禁止命令还生效；
  #+end_example

  当然，我这些理由都是shit，昨天通知这个报告给其它三个同事去用C++重新基于TXT结果生成，今天通报全公司我被炒鱿鱼了，而收到消
  息的我，正在医院陪郡主做检查，我当时那个心情啊!

  但我还是给BOSS写了个“检讨书”，希望能留在公司，也意识到自己的一些问题:
  #+begin_example
  1. 公司既然不准使用Python，干吗要使用，自以为是，了不起啊；
  2. 缺乏沟通，干吗不通报下准备使用Python，这样这个活的具体实现就交给C++熟练同事了，自己还能熟练C++；
  3. 发现命令模棱两可，干吗不说出来，说出来又不会死；
  #+end_example

  希望留在公司，是因为:
  #+begin_example
  1. 我在这个公司已经呆了一年多了，心里有了感情；
  2. 来的时候北京这边就3人，内心是当作一份事业去做的，虽然事实上我只是个临时工；
  3. 上司对我很好，同事对我也很好，我们的团队是非常好的团队，人人有才能，人人能吃苦，这是一个能创业的团队；
  4. 公司有核心竞争力，有前途；
  5. 郡主马上就生孩子，我需要稳定工作。
  #+end_example

  检讨书已经发了，也尽力去挽回，但很多事情也不是能顺人心的。毕业两年，这是第二份工作，想想一路走来也经历了不少事情：
  #+begin_example
  1.   毕业加入工作，      汉柏说好去天津工作，结果在北京工作；
  2.   第一份工作一个月，  开始使用Fedora至今，放弃Ubuntu；
  3.   第一份工作一个月，  放弃测试工程师岗位，加入公司初创的云计算部门；
  4.   第一份工作三个月，  云计算部门解散，经老常介绍加入公司战略产品中心，开发基于GNU/Linux裁剪的流控设备；
  5.   第一份工作六个月，  和同事出差广州，见到惠州移动机房,爬白云山，见到小德、赖正香、雪梅等；
  6.   第一份工作八个月，  单独出差广州；
  7.   第一份工作一年，    项目组解散，项目组长离职，同月加入敏弈金融工程；

  8.   第二份工作三个月，  换了两次office，紧张繁重的工作，为北京团队壮大而努力
  9.   第二份工作四个月，  郡主来北京，搬到新office，alex加入
  10.  第二份工作五个月，  介绍俩兰威、虎子加入敏弈，还清家里上学贷款，开始使用github.com，David加入；
  11.  第二份工作六个月，  边吃年夜饭边做8th
  12.  第二份工作七个月，  alex离开，
  13.  第二份工作八个月，  jpyu加入一个月离开，cindy，martin加入
  14.  第二份工作一年，    结婚，还清学校上学贷款,HuaChao离开；

  15.  第二份工作一个月，  搬到新office，victor加入一个月离开...
  16.  第二份工作二个月，  痛苦的一个月，各种杂七杂八的事情，旧秩序打破，新秩序建立
  17.  第二份工作三个月，  俩同学被突然开除，后又重新回来上班，开始用org-mode维护自己的博客；
  18.  第二份工作四个月，  我被要求离开，开始认真学习lisp;
  #+end_example

  平时挑水，不忘挖井。我在（想）做的几个小项目:
  #+begin_example
  1. ScanRpt，平时生成XLS和PDF报告都是基于TXT，对TXT报告根据config.ini文件定义的规则进行QA
  2. MBSearch, 用IPython parallel功能建立一个并行查询MBS fn数据的数据库系统，实验性项目
  #+end_example


  本来想在这个公司呆10年的（Amanda呆了10年多，Lily现在60多还在负责公司JSP网站)，那就找一家能呆久点的公司吧:
  #+begin_example
  1. 允许使用Python
  2. 愿意使用GIT管理
  3. 员工有时间照顾家人
  4. 愿意建立内部学习、共享渠道
  5. 最好是创业型，敢于信任员工
  6. 听到员工在学lisp，不会说shit
  7. 愿意给员工成长空间
  #+end_example

  坐等结果吧，没办法，要赶紧找工作啊，拖家带口的......

  ....

  结果出来了：
  #+begin_example
  1. 我可以留下；
  2. 保证我可以写C++；
  3. 只有能写C++的才是有用的人；
  4. 对我的印象就是个吊儿郎当的人...
  #+end_example

  对于第四点，印象的形成是有一次4th后（熬夜）修改了skype状态是“吃个饭，睡个觉..."，我没事改状态干啥？

  以后，就用C++了，我从来没有学过C++之外的其它语言，尤其是Python！！！

  说了很多气话，发了一通牢骚之后，我应该彻底反思，不管如何，这次是我自己做的不对。

  长期以来，对自己的要求不高，让自己一直在一堆低质量的代码堆里面爬滚，还对各种技术抱有投机心理，做事情不踏实，学技术不踏实。同时，做
  事情不够聪明，完全可以用一种很好的方式去完成，结果偏偏选择了一种最不好的方式。

  端正自己的态度，重新从基础学习，脚踏实地把技术学好，把事情做好！

  #+begin_example
  1. 细读林锐《高质量的C/C++编程》，养成好的编程习惯；
  2. 拜读《C++ Primer》一书，写点小程序，参与公司代码修改;
  3. 多写笔记，多看别人写的代码
  #+end_example

  #+begin_html
<!-- Duoshuo Comment BEGIN -->
<div class="ds-thread"></div>
<script type="text/javascript">
var duoshuoQuery = {short_name:"lesliezhu"};
(function() {
var ds = document.createElement('script');
ds.type = 'text/javascript';ds.async = true;
ds.src = 'http://static.duoshuo.com/embed.js';
ds.charset = 'UTF-8';
(document.getElementsByTagName('head')[0] 
		|| document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- Duoshuo Comment END -->
#+end_html
  
