* 一个新世界(08/24/2013)

  上周末送郡主回了家里，我也在家里呆了一周；这一周过的不算清闲，因为虽然请假在家，我还是有很多工作要做。在处理工作之余，我开始阅读
  自己打印的<<Common Lisp>>第二版的上册，看了几章也不知道自己在看什麽；为了解惑，加入了几个讨论Lisp的QQ群，知道有一Lisp方言叫“Shen”，
  总之，一切都是美好的开端，新生命新世界的诞生。我内心满怀期待，尽管有一些惴惴不安。

  明天要回北京，今天却遇到被炒鱿鱼的危机。起因是上周末要给客户生成一个报告，我使用Python语言生成的。之前公司说过不准使用Python，我违反
  了规定。至于不准使用Python的原因，就不方便说了。

  给BOSS写了个“检讨书”，希望能留在公司，也意识到自己的一些问题,希望留在公司，是因为:
  #+begin_example
  1. 我在这个公司已经呆了一年多了，心里有了感情；
  2. 来的时候北京这边就3人，内心是当作一份事业去做的，虽然事实上我只是个临时工；
  3. 上司对我很好，同事对我也很好，我们的团队是非常好的团队，人人有才能，人人能吃苦，这是一个能创业的团队；
  4. 公司有核心竞争力，有前途；
  5. 郡主马上就生孩子，我需要稳定工作。
  #+end_example

  坐等结果吧，没办法，要赶紧找工作啊，拖家带口的......

  好在还能留在公司，我应该彻底反思，不管如何，这次是我自己做的不对。

  长期以来，对自己的要求不高，让自己一直在一堆低质量的代码堆里面爬滚，还对各种技术抱有投机心理，做事情不踏实，学技术不踏实。同时，做
  事情不够聪明，完全可以用一种很好的方式去完成，结果偏偏选择了一种最不好的方式。

  端正自己的态度，重新从基础学习，脚踏实地把技术学好，把事情做好！

  #+begin_example
  1. 细读林锐《高质量的C/C++编程》，养成好的编程习惯；
  2. 拜读《C++ Primer》一书，写点小程序，参与公司代码修改;
  3. 多写笔记，多看别人写的代码
  #+end_example

  生活中不应该有太多的抱怨，积极乐观的发现生活的美好，发现别人的优点，学习别人的长处，这样才能进步！

  以后，博客中不要涉及太多私人感情，多写有价值的技术博客，迎接一个新世界！

  #+begin_html
<!-- Duoshuo Comment BEGIN -->
<div class="ds-thread"></div>
<script type="text/javascript">
var duoshuoQuery = {short_name:"lesliezhu"};
(function() {
var ds = document.createElement('script');
ds.type = 'text/javascript';ds.async = true;
ds.src = 'http://static.duoshuo.com/embed.js';
ds.charset = 'UTF-8';
(document.getElementsByTagName('head')[0] 
		|| document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- Duoshuo Comment END -->
#+end_html
  
