* 夜读史记(07/19/2013)

   史记分为本纪、表、书、世家和列传:
   - 本纪，纪录帝王言行
   - 表，列出年谱世系、史事
   - 书，记录各种制度和重要书籍
   - 世家，记录王侯将相的事迹，多为特别重要人物
   - 列传，记录王侯将相之外的各方面代表人物

   *伯夷列传第一*

   列传以伯夷列传为第一篇，越看越看不懂，司马迁发的是什麽感慨？

   尝试翻译:

   求学的人虽然博览群书，但还是需要参考*六艺*。《诗经》和《尚书》虽然残缺，但虞夏之间的文化可见一斑。尧将逊位，让给虞舜，虞舜和禹之间，
   所有的诸侯都推荐，于是尝试让虞舜执政，数十年后，百业兴盛，然后才彻底将权利移交给他。移交天下大权，王者体统和天下如此之难。却有人说
   尧将天下传给许由，许由不接受并深感耻辱，于是归隐。到了夏朝的时候，又有卞随、务光的故事。这是怎么流传开来的呢？

   太史公：我登山箕山，上面盖有许由的坟冢。孔子列出古代的仁者、圣者、贤人，如吴太伯、伯夷的故事非常详细。我奇怪既然许由、务光的义气
   如此之高，对于他们的文章却几乎是很少的概述，这又是为何呢？

   孔子说，伯夷、叔齐不念别人以前做的恶事，怨恨就越来越少。坚持仁义并得到仁义，又有什麽怨恨呢？
   
   我很同情伯夷的情意，光是看流传的诗歌就值得另眼相看了。他的传书是：

   伯夷、叔齐，是孤独君的两个儿子。父亲想立叔齐为王，到父亲离世的时候，叔齐将王位让给伯夷。伯夷说，这是父亲之命，就逃走而不接受王位。
   叔齐也不肯接受王位而逃走。于是，国家就立叔齐的小儿子为王。这时候，伯夷、叔齐听说西伯侯姬昌懂养生之道，便去归附。等到了西岐，姬昌
   已经离世，武王即位为文王，东进伐纣。伯夷、叔齐拦住其行军的马队进谏说，父亲死了不好好厚葬，却动兵戈，是孝吗？作为臣子却去杀害君主，
   是讲仁义吗？ 文王的手下想杀死他俩，太公姜子牙说，这是义士。把他俩扶起来并让他俩安全离开。待武王已经平定殷王朝，天下已经以周为王，
   但伯夷、叔齐却以此为耻，坚持君臣大义而不吃周朝的粮食，归隐于首阳山，以蔷薇为食。等到快饿死的时候，作歌吟唱，内容是： 登上那边的
   山啊，采蔷薇为食；以暴政代替暴政呢，不知道这样是不行的吗？神农、虞舜、夏禹的朝代突然就过去了，我们最终会怎么样呢？岁月蹉跎，这就
   老了！ 于是，饿死在首阳山。

   由此看来，他们心中没有怨恨吗？

   有人说，老天爷没有亲疏，只帮助善人。像伯夷、叔齐应该是善人吧，坚持仁义、洁身自好，却被饿死。何况孔子七十二学生，孔子唯独推崇
   颜回好学。但颜回也常常腹中空空挨饿，糟糠也吃过，还早早就死了。 老天爷施恩回报善良之人就是这样吗？ 盗跖天天杀害无辜之人，以人的
   肝脏为食，暴戾横行，聚集党羽数千人横行天下，却能够寿终无碍。这又是急得哪门子德呢？ 这就是他为什麽这么人人皆知吧。

   讲到近年来，没有节操规矩、专门做坏事的人，却能一生享受安逸富贵，还子孙相传。有的人谨慎做事、规规矩矩做人却遭遇灾祸，这样的人多了
   去了。我很疑惑，所谓的天道，是否真的存在？

   孔子说，秉承的道义不同就不会为共同的目标而努力；也就是人各有志罢了。所以说，如果富贵可以到手，哪怕当个牵马的随从，我也愿意；如果
   富贵不可求，我就去追寻我的喜好。只有等到寒冷的年月，这样才能知道松柏是最后凋零的；只有当举世之人都混沌度日的时候，坚持洁身自好的
   人才看的出来，怎么可以厚此薄彼呢？

   人啊，就怕到死的时候还默默无闻。贾谊说，贪婪的人一生追求钱财，壮烈的人追求名声，好大喜功的人直到临死还迷恋权位，老百姓只能苟且偷生
   。伯夷、叔齐虽然很贤明，却是因为孔子而流芳百世；颜回虽然好学，也是因为孔子才名言四海。

   那些正默默拼搏的人，坚持或者放弃都是自己的决定，但大部分是到死也无法实现自己的理想，真是悲壮啊！普通之人，要想名扬天下，就要凭借他人的帮助，否则怎么能流芳百世呢？

   
