** 时光

   06/02/2013

   此刻的我，刚刚和郡主吃夜宵回来，因为六一买了IPAD保护套，我们很轻松的看了一会《过把瘾》电视剧；倦意袭来，我又坐到电脑前,开始整理
   这个在github上建立的[[http://lesliezhu.github.com][博客]].

   我是个很没有毅力的人，因此我准备做一件大多数父母都会做的事，那就是让孩子去做自己做不到的事情。曾子云“君子不可以不弘毅，任
   重而道远！”；我将来的孩子应该就会叫弘毅，希望他做个有毅力的人。

   虽然没有什麽毅力，却很贪婪，懒、好吃、好玩，所以身体肥胖却无法减肥；同时，我似乎很好学，什麽都想学下，但总是半途而废。这
   样的事情长期困扰着我，我常常想着自己通过如何的学习掌握某项本领，却总是成为一种想法。

   不仅仅没有毅力，没有行动力也是我的致命伤。贪多嚼不烂，我常常因为目标太多而导致没有任何行动，好不容易有个行动，却容易被中断，精力
   无法长期保持集中，最后的结果是很多事情虎头蛇尾，变成没有毅力的表现。

   对于我这种人，最好的方法，就是一次只做一件事情，一次只学一项本事。

   说起来，我想学习的本领可多着呢，真想在这里大言不惭的列出来:

   - *emacs*
     
   自打我知道这个世界上还有一个GNU/Linux开始，我就知道了Emacs；但我没有一个好的开端。我总是想着我学会了emacs的各种配置，然后使用
   emacs做很多事情，而这写配置不是那么容易的，尤其是我还不知道github的时候。 我本来应该先用起来，不要管什麽配置，不要管什麽中文
   处理，就仅仅是编辑；随着使用的熟练，真正的需求会慢慢浮现，这个时候再深入学习才会事半功倍。从org-mode开始学，写文档真是太棒了，因为她,
   我喜欢上了写文档，一步一步熟悉后，再学习emacs-lisp编程。
   
   - *common lisp*
     
   先是因为emacs知道还有一种叫lisp的语言，然后看了“如何成为黑客”里面讲的lisp多么厉害，之后是“黑客与画家”里面对lisp的神圣化。我觉得我
   必须学习这门语言，既然知道自己要学习它，那么为什麽不立即行动呢？担心不好找工作？或者太难？

   - *Node.js*
   

   开始是工作上遇到javascript，自己一点不会，然后是看微博上知道node.js比较新的技术，看了看挺感兴趣。

   - *吉他*
     

   如果有那么一件事情能让我暂时忘记编程，那就是吉他了，可惜我不会；我永远忘不了那天下午，我起来准备去上班，阳光照进屋子，洒在吉他
   上，我波动了下吉他，那声音真叫人感动，于是我背着双肩包上班去了。那天真美好。

   - *游泳*


   小时候家里不让下河游泳，因为我一个叔叔，在他10岁的时候玩水淹死了。我和哥哥因为玩水，被打了一顿，饿了一天饭。想游泳，没有理由。

   - *写作*


   喜欢郁达夫，想提高自己的修辞，多看书，多写作，口才不行就只能写了。

   - *研究日本*


   看过《菊与刀》、《日本人与日本论》、《国破山河在》，很仰慕将百里，真是达芬奇式的人物。戴季陶说日本人把中国人放在手术室里研究了
   几千年。现在的我们，除了国仇之恨，却忘记了“知己知彼”的道理，因此，要了解日本、学习日本、研究日本。该做的事情，永远逃不掉，中国
   人100年前就开始研究日本，却基本没有什麽成果，目前就知道一个萨苏不错，其它的呢？看着加藤加一都在中国出书好几本了，心里不是滋味。

   - *王阳明*

   
   第一次知道王阳明，是看一出昆曲，讲的是王阳明平定赣州的盗贼；印象很深的是王阳明让盗贼脱去裤子，盗贼羞愧，王阳明则说“你虽然是盗贼，
   却还有羞愧之心，即是心存良知之人，心存良知就可以改邪归正”，于是招安了。 后来看《明朝那些事》里面把王阳明列为明朝第一条好汉，还买
   了本钱穆写的《阳明学》，要好好读读.


   
   我这个人很好笑，总是把工作带入生活，白白错过陪伴家人的时光；时光总是美好的，尤其是过去的。如果我知道我此时此刻在做什麽，我就不会
   那么的怀念过去。

   
     
   
   

   

   


